DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
  ID INT NOT NULL,
  NAME VARCHAR(100),
  DEPARTMENT VARCHAR(100),
  CREATED_AT DATE,
  PRIMARY KEY (ID)
);

CREATE TABLE members (
  contract_id BIGINT PRIMARY KEY,
  member_id BIGINT,
  product_id BIGINT,
  card_number VARCHAR(20),
  registration_date DATE
);